---
# This playbook provisions the docker topology.

- name:  "schema check and Pre Provisioning Activities on topology_file"
  hosts: localhost
  gather_facts: True
  roles:
    - { role: 'common' }

- name:  "Provisioning Docker resources"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'docker' }

- name: "Gather resources to the RunDB"
  hosts: localhost
  gather_facts: False
  roles:
    - { role: 'gather_resources' }
